Driver.destroy_all

Driver.create(:name => "Max Verstappen", :country => "Netherlands", :team => "Red Bull Racing", :dob => "1997/09/30", :current_ranking => 1, :points => 1449, :podiums => 55, :image => "https://www.formula1.com/content/fom-website/en/drivers/max-verstappen/_jcr_content/image.img.1920.medium.jpg/1617101447981.jpg", :bio => "He’s Max by name, and max by nature. Arriving as Formula 1’s youngest ever competitor at just 17 years old, Verstappen pushed his car, his rivals and the sport’s record books to the limit. The baby-faced Dutchman with the heart of a lion took the Toro Rosso – and then the Red Bull – by the horns with his instinctive racing style. F1’s youngest points scorer soon became its youngest race winner – at the age of 18 years and 228 days – with an opportunistic but controlled drive on debut for Red Bull in Barcelona 2016. A true wheel-to-wheel racer, another stunning drive in Brazil from the back of the pack to the podium on a treacherous wet track kept the plaudits coming. Verstappen’s no-holds-barred attitude and hard defending have sometimes landed him in hot water with his peers and paymasters. But the mistakes that initially marred his potential have given way to maturity, while the bravado and energy that make him a blockbuster talent have remained – and the victories have kept on coming. The son of former F1 driver Jos Verstappen and super-quick karting Mum Sophie Kumpen, racing runs through his genes. Despite moving out of Dad’s house to live in Monaco, Verstappen remains close to his family, and though he’s not afraid to speak his mind, he can still be surprisingly shy. The expectations for the next generation’s leading light are sky high – but with Verstappen there’s a feeling that the sky’s the limit.")
Driver.create(:name => "Lewis Hamilton", :country => "United Kingdom", :team => "Mercedes", :dob => "1985/01/07", :current_ranking => 2, :points => 4053, :podiums => 177, :image => "https://www.formula1.com/content/fom-website/en/drivers/lewis-hamilton/_jcr_content/image.img.1920.medium.jpg/1617101457462.jpg", :bio => "‘Still I Rise’ – these are the words emblazoned across the back of Lewis Hamilton’s helmet and tattooed across his shoulders, and ever since annihilating expectations with one of the greatest rookie performances in F1 history in 2007, that’s literally all he’s done: risen to the top of the all-time pole positions list ahead of his hero Ayrton Senna, surged into first place in the wins column surpassing the inimitable Michael Schumacher, and then matched the legendary German’s seven world titles. Is he the G.O.A.T? Few would deny that he’s in the conversation – and what’s more he’s got there his way, twinning his relentless speed with a refusal to conform to stereotypes for how a racing driver should think, dress or behave. Respect is hard earned in F1, but Hamilton – now Sir Lewis Hamilton to be precise – has it from every one of his peers. Why? Because they know that whatever the track, whatever the conditions, whatever the situation, when his visor goes down and the lights go out, it’s Hammertime.")
Driver.create(:name => "Valtteri Bottas", :country => "Finland", :team => "Mercedes", :dob => "1989/08/28", :current_ranking => 3, :points => 1697, :podiums => 65, :image => "https://www.formula1.com/content/fom-website/en/drivers/valtteri-bottas/_jcr_content/image.img.1920.medium.jpg/1617101457255.jpg", :bio => "Learning his craft on Finnish roads of ice and snow, he was born to be a Grand Prix racer. Bottas explains that if you can drive on the frozen roads of his homeland then you can drive anywhere. Then there’s the Finnish mentality –reserved, diligent and calm the fast lane of F1 doesn’t faze him. Making his F1 debut with Williams in 2013, Bottas soon became part of the family. Points and podiums followed with the reliable racer even amassing the most points without a win, a record he resented but that showcased his ability. The fact the Finn was such a points machine saw him suddenly promoted to the most coveted seat in F1 - Nico Rosberg’s vacant championship-winning seat at Mercedes. Bottas blossomed at the Silver Arrows in 2017, unleashing his pace to clock up personal pole positions and victories as well as a team championship for the famous Mercedes marque alongside Lewis Hamilton. He even tied with Hamilton and Sebastian Vettel with 13 podiums. For a shy guy, it brought a confidence boost and a new swagger – albeit in a very demur Finnish fashion. He would need all that confidence in 2018 – a season Bottas described as his worst in F1, as he took zero wins to Hamilton’s 11. That, though, was a reflection more of his team mate’s brilliance thank of any shortcomings on his own part. Bottas stepped it up a level in 2019, four victories securing a convincing second in the championship behind Hamilton, but that dropped to two wins to his team mate's 11 in 2020. Now he must dig even deeper if he’s to regularly beat the man on the other side of the garage - and fend off the Red Bulls and Ferraris - and drive home as the fourth Finnish world champion.")
Driver.create(:name => "Sergio Perez", :country => "Mexico", :team => "Red Bull Racing", :dob => "1990/01/26", :current_ranking => 4, :points => 856, :podiums => 14, :image => "https://www.formula1.com/content/fom-website/en/drivers/sergio-perez/_jcr_content/image.img.1920.medium.jpg/1617101446970.jpg", :bio => "He’s the fighter with a gentle touch from the land of the Lucha Libre. Perez’s reputation in F1 has been built on opposite approaches to Grand Prix racing. On the one hand, he is a punchy combatant who wrestles his way through the pack and into the points. Never afraid to add a bit of spice to his on-track encounters, even his team mates don’t always escape the Mexican’s heat. Then on the other hand, Perez is a smooth operator, a master at managing tyres to eke out extra performance and give him the upper hand on strategy. A firm favourite on the grid after his time with Sauber, McLaren, Force India and Racing Point, Perez has matured into an analytical racer and team leader. A proud countryman, the Guadalajara gunslinger has amassed more points than any other Mexican in the history of F1. In Sakhir 2020 he also matched hero and compatriot Pedro Rodriguez by taking the chequered flag in first – a performance that landed him a shot at the title with Red Bull. More victories may not be assured, especially with Max Verstappen as team mate. But Perez working hard and racing with his heart are.")
Driver.create(:name => "Lando Norris", :country => "United Kingdom", :team => "McLaren", :dob => "1999/11/13", :current_ranking => 5, :points => 295, :podiums => 5, :image => "https://www.formula1.com/content/fom-website/en/drivers/lando-norris/_jcr_content/image.img.1920.medium.jpg/1617101457428.jpg", :bio => "Lando Norris may not be named after Star Wars rebel Lando Calrissian - his Mum just liked the moniker - but he has flair and fighting spirit in bountiful supply. McLaren had the British teenager on their books for two years before fast-tracking him into F1’s galaxy of stars in 2019. A firecracker in his junior career, with a penchant for pole positions and wheel-to-wheel tussles, Norris didn’t let them down. Paired with the highly-rated – and far more experienced – Carlos Sainz, his rookie season was impressive, edging the Spaniard in their head-to-head qualifying battle, scoring points on 11 occasions, and only narrowly missing out on a top-10 championship placing. It was a similar pattern in 2020, with the affable Brit securing a maiden podium and moving up to ninth overall. An exciting talent on track, away from it Norris brims with a modest charm and an artistic side sees him design and paint his own race gear as a hobby. The focus for the future is allying artistry and ambition on track as McLaren rely on the promise of youth to take them back to the top. Norris hopes the downforce will be with him…")
Driver.create(:name => "Charles Leclerc", :country => "Monaco", :team => "Ferrari", :dob => "1997/10/16", :current_ranking => 6, :points => 529, :podiums => 13, :image => "https://www.formula1.com/content/fom-website/en/drivers/charles-leclerc/_jcr_content/image.img.1920.medium.jpg/1617101453619.jpg", :bio => "Born in the Mediterranean idyll of Monaco, Leclerc arrived in F1 on a tidal wave of expectation. Practically peerless on his way to the GP3 and Formula 2 crowns, he showcased a dazzling array of skills from scorching pole positions, commanding victories – even when his car caught fire twice at Silverstone – to an ability to muscle his way through the pack. Winning back-to-back championships also taught Leclerc how to handle pressure, another useful tool in the big pond of Formula 1 racing. Leclerc may have quit school early, but he looks every inch the complete driver. World champions Lewis Hamilton and Sebastian Vettel have even gone on record to say Leclerc is the real deal – and it’s not often they agree on anything… Stepping up to F1 in 2018, Leclerc showed flashes of ballistic pace on Saturdays and racing brilliance on Sundays, dragging his Sauber beyond its limits – and earning himself a money-can’t-buy race seat at Ferrari for 2019, stepping into the shoes of the Scuderia’s last world champion, Kimi Raikkonen. There he immediately put the cat among the proverbial pigeons, unafraid to go wheel-to-wheel with established number one, Sebastian Vettel. A maiden F1 victory at Spa was followed by another a week later on Ferrari’s hallowed home turf of Monza. The tifosi had found another new hero – who then became the first man to out-score Vettel over a season with the Scuderia, a feat he repeated in crushing fashion the following year. Out of the car, Leclerc is modest and thoughtful - but then he is on his own very personal mission. This exciting young talent is racing for his late father Herve and his friend and mentor Jules Bianchi, the F1 driver who died in 2015. On the evidence so far, he is doing them both proud.")
Driver.create(:name => "Carlos Sainz", :country => "Spain", :team => "Ferrari", :dob => "1994/09/01", :current_ranking => 7, :points => 494, :podiums => 5, :image => "https://www.formula1.com/content/fom-website/en/drivers/carlos-sainz/_jcr_content/image.img.1920.medium.jpg/1617101457421.jpg", :bio => "He’s the matador from Madrid racing royalty. Entering F1’s Bull Ring paired alongside Max Verstappen at Toro Rosso in 2015, Sainz quickly showed his fighting spirit. A tenacious racer, Sainz puts the car on the edge as he hustles his way through the pack. No wonder he’s earned the nickname Chilli. But the Spaniard is intelligent as well as instinctive, thinking his way through a race and into the points. This calm temperament follows him off track where he remains unfazed by the pressures of forging a Grand Prix career with a famous name. Sainz is the son of double World Rally champion, also his namesake, and has brought some of Dad’s driving skills to the F1 circuit – junior loves a delicious dose of drift for one. After following in his famous father’s tyre tracks, Sainz has had big racing boots to fill – first at McLaren where he replaced his childhood hero Fernando Alonso, and now at Ferrari, in the seat formerly owned by Sebastian Vettel. It is never easy living in the shadow of sporting giants, but Sainz has shown the drive and disposition to deal with it. Vamos!")
Driver.create(:name => "Daniel Ricciardo", :country => "Australia", :team => "McLaren", :dob => "1989/07/01", :current_ranking => 8, :points => 1264, :podiums => 32, :image => "https://www.formula1.com/content/fom-website/en/drivers/daniel-ricciardo/_jcr_content/image.img.1920.medium.jpg/1617101458318.jpg", :bio => "The self-styled “Honey Badger” is fuzzy on the outside and feisty on the inside. Drivers beware because behind Ricciardo’s laidback persona and big grin is a razor-sharp racer with a bite. The Australian combines all-out speed with impressive race craft. Never afraid to push to the limits if it means pulling off a pass, Ricciardo is a proven race-winner for Red Bull, capable of consistently finishing at the business end of the championship table. A regular podium-finisher, Ricciardo has christened the steps around the world with a dousing of Aussie culture – the ‘Shoey’ – as he quaffed champagne from a soggy racing boot. Yes it’s goofy, but the trademark celebration illustrates why he is loved for his sense of humour but never underestimated on track. His career’s next move to Renault’s works team brought fresh challenges for the Perth pilot, but failed to deliver his dream of following Jack Brabham and Alan Jones as the next world champion from Down Under. And in 2021 he hopes a new chapter with the Mercedes-powered McLaren team might just change that. But whatever happens, Ricciardo is sure to keep on smiling.")
Driver.create(:name => "Pierre Gasly", :country => "France", :team => "AlphaTauri", :dob => "1996/02/07", :current_ranking => 9, :points => 273, :podiums => 3, :image => "https://www.formula1.com/content/fom-website/en/drivers/pierre-gasly/_jcr_content/image.img.1920.medium.jpg/1617101447487.jpg", :bio => "If there’s one man who knows how big a rollercoaster ride an F1 driver’s career can be, it’s Pierre Gasly! The flying Frenchman was called up to make his 2017 debut in Malaysia in place of Daniil Kvyat and, after proving his mettle, he was named a Toro Rosso driver the following year.  A further 21 races into his fledgling career, Gasly was moved up again – this time to replace Red Bull big gun Daniel Ricciardo. Gasly seemed to have a knack of being in the right place at the right time – a quality that’s equally handy on track. A series of impressive 2018 performances for Toro Rosso – including a brilliant fourth place in Bahrain – showed exciting promise for what he might do with the ‘A’ team in 2019. Unfortunately that promise only appeared in flashes – and he quickly suffered from unfavourable comparisons with superstar team mate Max Verstappen. So much so that after the summer break, he was sent back to Toro Rosso, with another young up-and-comer – Alex Albon – being given a shot in the ‘senior’ Red Bull seat. But Gasly bounced back, as only Gasly can. In the season’s remaining nine races he scored almost as many points as team mate Kvyat managed over the entire year – and secured his best-ever race result with P2 in Brazil. That trajectory continued in 2020, peaking with an emotional maiden win at the renamed AlphaTauri team’s home race in Italy. The question now is can he maintain momentum and earn himself another shot at the F1 bigtime…")
Driver.create(:name => "Fernando Alonso", :country => "Spain", :team => "Alpine", :dob => "1981/07/29", :current_ranking => 10, :points => 1957, :podiums => 97, :image => "https://www.formula1.com/content/fom-website/en/drivers/fernando-alonso/_jcr_content/image.img.1920.medium.jpg/1617101458141.jpg", :bio => "Michael Schumacher was the undisputed king of Formula 1 in the early 2000s, picking up wins and championships at a rate that was simply unheard of at the time. It was going to take someone very special to topple the Ferrari legend from his throne – and that it was Fernando Alonso who did it, tells you all you need to know about the Spaniard. Fiercely competitive, Alonso is not shy about his talent, rating himself as 9/10 “in everything”, and few in the know would disagree, with his performances in F1 characterised by blistering speed, brilliant tactical thinking, exemplary race craft, a razor-sharp eye for detail and a relentless determination to win. A serial record breaker in his day, he was – at one time – F1’s youngest polesitter, race winner, world champion and double world champion as he gobbled up success with the Renault team. Even Alonso couldn’t continue that amazing run in his later career though, failing to add another title to his collection despite spells at McLaren and Ferrari. But after two years away from Formula 1 racing – and now with two Le Mans wins in his pocket – Alonso is back with Alpine in 2021. And he has unfinished business with F1…")
Driver.create(:name => "Esteban Ocon", :country => "France", :team => "Alpine", :dob => "1996/09/17", :current_ranking => 11, :points => 244, :podiums => 2, :image => "https://www.formula1.com/content/fom-website/en/drivers/esteban-ocon/_jcr_content/image.img.1920.medium.jpg/1617101457663.jpg", :bio => "If there’s one word that dominates Esteban Ocon’s career, it’s ‘sacrifice’. Back when he was just a promising karter, Ocon’s parents sold their house, put their jobs on hold, and began a life on the road, living in a caravan and travelling from circuit to circuit to support their son’s burgeoning career. Sacrifice, see – but it worked. 2014 saw Ocon break through in the world of single-seaters, as he beat a certain Max Verstappen to the European F3 title. Backed by Mercedes, he won the GP3 title the following year and was halfway through a season of DTM in 2016 when he was offered the chance to replace Rio Haryanto at the minnow Manor team from the Belgian Grand Prix onwards. That opportunity led to a full-time seat the following year with Force India, where his wheel-to-wheel duels with highly-rated team mate Sergio Perez quickly marked him out as a rising star. But when Lawrence Stroll, father of racer Lance, stepped in midway through 2018 to secure the squad’s financial future, the writing was on the wall for Ocon, who was moved aside at the end of the year to allow Stroll Jnr to join from Williams. Ocon bided his time, though, and after a year on the sidelines as Mercedes’ reserve driver, he found his way back into a race seat with Renault in 2020. Nothing in Ocon’s motorsport career has come easy – but if Ocon has managed to return to the F1 grid, it’s through a combination of self-belief, determination and a talent that’s up there with the very best.")
Driver.create(:name => "Sebastian Vettel", :country => "Germany", :team => "Aston Martin", :dob => "1987/07/03", :current_ranking => 12, :points => 3054, :podiums => 122, :image => "https://www.formula1.com/content/fom-website/en/drivers/sebastian-vettel/_jcr_content/image.img.1920.medium.jpg/1617101458077.jpg", :bio => "Born and raised a Bull, then a Prancing Horse, and now the face of Aston Martin’s Formula 1 revival, F1's poster boy of early achievement had won more than all but two drivers in history by the time he was just 26, including back-to-back world titles between 2010 and 2013. Vettel’s trademark is pure pace – and of course his one-finger victory salute. In the chase to the chequered flag, he likes to lead from the front and just like his hero, Michael Schumacher. But for all his competitive streak, Vettel has a playful side too and has been known to let loose with a spot of Beatles karaoke - and baby can he drive a car. Alongside his four world crowns he can boast more than 50 pole positions and race victories, ranking him – statistically - above many of the biggest names in F1 history. No wonder then that he has twice been hand-picked to return some of Grand Prix oldest names to glory. Following his move to Maranello, that mission didn’t exactly go to plan as Vettel’s rivalry with Lewis Hamilton intensified. Then came an additional thorn in his side – young-gun Ferrari team mate Charles Leclerc, the first man to outscore him over a season at the Scuderia. Now, as he takes on a new challenge as Aston Martin’s team leader, Vettel will need to call on all his speed and experience if he’s to reassert himself over his rivals – and to re-establish his reputation as one of the sport’s all-time greats.")
Driver.create(:name => "Lance Stroll", :country => "Canada", :team => "Aston Martin", :dob => "1998/10/29", :current_ranking => 13, :points => 168, :podiums => 3, :image => "https://www.formula1.com/content/fom-website/en/drivers/lance-stroll/_jcr_content/image.img.1920.medium.jpg/1617101447217.jpg", :bio => "There is no such thing as too much too soon for Stroll, a teenage sensation with a wet weather predilection. One of the cool kids on the grid, Stroll was unveiled shortly after his 18th birthday by Williams – before he finished high school and got his road licence. Stroll meant business in his debut 2017 season, setting records on the way. An opportunistic racer he bounded onto the podium in Baku, the youngest rookie to do so. As the son of a wealthy entrepreneur, Stroll is used to a champagne lifestyle but now he knows the fizz tastes all the sweeter on the rostrum. Then in Monza he mastered the downpours to become the youngest driver in history to line up on the front row.")
Driver.create(:name => "Yuki Tsunoda", :country => "Japan", :team => "AlphaTauri", :dob => "2000/05/11", :current_ranking => 14, :points => 20, :podiums => 0, :image => "https://www.formula1.com/content/fom-website/en/drivers/yuki-tsunoda/_jcr_content/image.img.1920.medium.jpg/1617101457751.jpg", :bio => "In the entire history of Formula 1, no Japanese driver has ever won a World Championship Grand Prix. Could Yuki Tsunoda be the first? Red Bull certainly think so, with the youngster very much on the path to their senior team if he continues to impress as he has done over the past few years.")
Driver.create(:name => "George Russell", :country => "United Kingdom", :team => "Williams", :dob => "1998/02/15", :current_ranking => 15, :points => 19, :podiums => 1, :image => "https://www.formula1.com/content/fom-website/en/drivers/george-russell/_jcr_content/image.img.1920.medium.jpg/1617101470404.jpg", :bio => "He’s the driver with the motto: “If in doubt, go flat out”. George Russell has lived by it in his F1 career to date, out-qualifying seasoned team mate Robert Kubica at all 21 Grands Prix in his rookie season, and repeating the feat against Nicolas Latifi in 2020 - and proving Williams right in identifying him as a hard worker and a tenacious talent. That brilliant baseline speed served Russell well as he totted up titles on his way to Formula 1. The Briton stormed to the 2017 GP3 championship and delivered the 2018 Formula 2 crown under immense pressure. Spotting his potential, world champions Mercedes swooped to sign him to their junior programme in 2017, when Russell already had a DTM deal on the table. He banked more experience with practice sessions with Force India and tests for the Silver Arrows, before landing his Mercedes-powered Williams race drive. A refusal to cede ground to his rivals - and commitment to a tricky pass – underpins Russell’s winning mentality. And it’s what got him the call-up to replace Lewis Hamilton for a one-off Mercedes appearance for Sakhir 2020 when the reigning champ was struck down by Covid-19. That star turn saw Russell miss out on pole by just 0.026s and then outrace Mercedes stalwart Valtteri Bottas. Only a bungled pit stop and a heart-breaking late puncture prevented a near-certain maiden win for the up-and-coming super-sub. And though he’s yet to score a point with Williams, he wants to put that right in 2021 – all the while keeping his eye on the bigger prize of a top-team drive in the future. As always, ‘Russell the Rocket’ will be going flat out.")
Driver.create(:name => "Nicholas Latifi", :country => "Canada", :team => "Williams", :dob => "1995/06/29", :current_ranking => 16, :points => 7, :podiums => 0, :image => "https://www.formula1.com/content/fom-website/en/drivers/nicholas-latifi/_jcr_content/image.img.1920.medium.jpg/1617101447797.jpg", :bio => "Thirteen is an advanced age to begin your karting career these days. But that’s how old Toronto native Nicholas Latifi was when he took his first steps in motorsport. Just 11 years later, he became a fully-fledged Formula 1 driver. That ascension into racing's top category was largely thanks to his most impressive season to date in Formula 2 in 2019, with Latifi – who’d finished a disappointing ninth in the series’ 2018 standings – pulling up his bootstraps to claim second in the championship. That result, combined with the Williams/Robert Kubica union failing to mesh in 2019, meant Williams made the call to promote their affable Canadian reserve driver to a full-time drive alongside George Russell for 2020. Latifi’s first taste of F1 machinery actually came all the way back in 2017, when he was given a test by Renault. Further duties with Force India followed in 2018 before he joined the Williams family in 2019. It was an annus horribilis for the squad, no doubt – but Latifi’s straightforward, friendly attitude and insightful feedback helped swing the vote in his favour for 2020. Now, after a rookie season living in Russell’s shadow, the goal is to show that that his eye-catching F2 year wasn’t just a fluke, and prove that he really has got what it takes to mix it with the best drivers in the world.")
Driver.create(:name => "Kimi Raikkonen", :country => "Finland", :team => "Alfa Romeo Racing", :dob => "1979/10/17", :current_ranking => 17, :points => 1869, :podiums => 103, :image => "https://www.formula1.com/content/fom-website/en/drivers/kimi-raikkonen/_jcr_content/image.img.1920.medium.jpg/1617101460196.jpg", :bio => "He’s the world-famous racing driver who just wants to be left alone. Raikkonen has a cult status in F1 like no other driver of his generation, but if you ask him why he just shrugs. Maybe it’s because of the rugged, raw talent that inspired Sauber to give him his debut in 2001 – and re-sign him for 2019. Or the fast and fearless racing that led to memorable McLaren wins. Or the never-say-die attitude that clinched the 2007 world title for Ferrari by a single point. Or maybe it’s because this is the ‘Iceman’ who jumped straight into a Jacuzzi on his yacht after retiring in Monaco and who enjoyed an ice cream when a soggy Malaysian GP was red-flagged but still live. Raikkonen literally does his talking on track. Out of the car, the Finn is famously taciturn. Although those who know him well say privately he is an amusing bon viveur, as well as a devoted family man. Meanwhile, his legions of loyal fans have to rely on revelations in his radio transmissions. And maybe Raikkonen himself best summed up the enigma of the Iceman when he said on the airwaves: “Leave me alone, I know what I’m doing.”")
Driver.create(:name => "Antonio Giovinazzi", :country => "Italy", :team => "Alfa Romeo Racing", :dob => "1993/12/14", :current_ranking => 18, :points => 19, :podiums => 0, :image => "https://www.formula1.com/content/fom-website/en/drivers/antonio-giovinazzi/_jcr_content/image.img.1920.medium.jpg/1617101458903.jpg", :bio => "He’s the Italian steed with speed from the stable of the Prancing Horse. Antonio Giovinazzi flies the flag for Italy as the motorsport mad nation champs at the bit for its next F1 star. The pilota from Puglia can punch his way through the pack and pull off a plucky pass. He showcased this natural racing acumen during a blistering 2016 GP2 campaign where he finished a close runner-up to team mate Pierre Gasly. Giovinazzi concedes he went from hero to zero after two races as a stand-in for Sauber in 2017 when a brilliantly composed F1 debut in Melbourne was followed by two shunts in Shanghai. But a stint as Ferrari reserve gave him time to re-group and reflect ahead of his first full season in 2019, paired alongside Kimi Raikkonen at Alfa Romeo. The notion of a home-grown racer with the iconic Alfa Romeo brand is irresistible to many – and Giovinazzi has laid claim to being the Italian for the job, after he out-qualified Raikkonen across the course of the 2020 season. Now his challenge is to out-race the Iceman…")
Driver.create(:name => "Mick Schumacher", :country => "Germany", :team => "Haas F1 Team", :dob => "1999/03/22", :current_ranking => 19, :points => 0, :podiums => 0, :image => "https://www.formula1.com/content/fom-website/en/drivers/mick-schumacher/_jcr_content/image.img.1920.medium.jpg/1617101458517.jpg", :bio => "Plenty of sons of former F1 drivers have joined the sport over the years – two have even emulated their fathers to become world champions – but carrying the Schumacher name is surely an extra level of pressure for Mick, given his father Michael’s extraordinary achievements in Formula 1.")
Driver.create(:name => "Nikita Mazepin", :country => "Russian Autobile Federation", :team => "Haas F1 Team", :dob => "1999/03/02", :current_ranking => 20, :points => 0, :podiums => 0, :image => "https://www.formula1.com/content/fom-website/en/drivers/nikita-mazepin/_jcr_content/image.img.1920.medium.jpg/1617101458189.jpg", :bio => "Nikita Mazepin might be bringing a healthy chunk of budget with him to the Haas team, but don’t be fooled into thinking he hasn’t also got the driving chops to go with it. The Russian – the fourth to compete in F1 after Vitaly Petrov, Sergey Sirotkin and Daniil Kvyat – has an impressive CV in the junior formulas, finishing runner-up in the 2018 GP3 championship with four race wins.")

puts "#{Driver.count} entries created."


Track.destroy_all

Track.create(:name => 'Bahrain Grand Prix', :country => 'Bahrain', :track_type => 'Race circuit', :length => 5.412, :race_laps => 57, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Bahrain_Circuit.png')
Track.create(:name => 'Emilia-Romagna Grand Prix', :country => 'Italy', :track_type => 'Race circuit', :length => 4.909, :race_laps => 63, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Emilia_Romagna_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Portuguese Grand Prix', :country => 'Portugal', :track_type => 'Race circuit', :length => 4.360, :race_laps => 66, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Portugal_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Spanish Grand Prix', :country => 'Spain', :track_type => 'Race circuit', :length => 4.675, :race_laps => 66, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Spain_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Monaco Grand Prix', :country => 'Monaco', :track_type => 'Street circuit', :length => 3.337, :race_laps => 78, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Monoco_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Azerbaijan Grand Prix', :country => 'Azerbaijan', :track_type => 'Street circuit', :length => 6.003, :race_laps => 51, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Baku_Circuit.png.transform/9col/image.png')
Track.create(:name => 'French Grand Prix', :country => 'France', :track_type => 'Race circuit', :length => 5.842, :race_laps => 53, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/France_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Styrian Grand Prix', :country => 'Austria', :track_type => 'Race circuit', :length => 4.318, :race_laps => 71, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Styria_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Austrian Grand Prix', :country => 'Austria', :track_type => 'Race circuit', :length => 4.318, :race_laps => 71, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Styria_Circuit.png.transform/9col/image.png')
Track.create(:name => 'British Grand Prix', :country => 'United Kingdom', :track_type => 'Race circuit', :length => 5.891, :race_laps => 52, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Great_Britain_Circuit.png')
Track.create(:name => 'Hungarian Grand Prix', :country => 'Hungary', :track_type => 'Race circuit', :length => 4.381, :race_laps => 70, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Hungary_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Belgian Grand Prix', :country => 'Belgium', :track_type => 'Race circuit', :length => 7.004, :race_laps => 44, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Belgium_Circuit.png')
Track.create(:name => 'Dutch Grand Prix', :country => 'Netherlands', :track_type => 'Race circuit', :length => 4.259, :race_laps => 72, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Netherlands_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Italian Grand Prix', :country => 'Italy', :track_type => 'Race circuit', :length => 4.909, :race_laps => 53, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Italy_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Russian Grand Prix', :country => 'Russia', :track_type => 'Race circuit', :length => 4.086, :race_laps => 53, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Russia_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Turkish Grand Prix', :country => 'Turkey', :track_type => 'Race circuit', :length => 4.381, :race_laps => 58, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Turkey_Circuit.png.transform/9col/image.png')
Track.create(:name => 'United States Grand Prix', :country => 'United States', :track_type => 'Race circuit', :length => 5.513, :race_laps => 56, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/USA_Circuit.png')
Track.create(:name => 'Mexico City Grand Prix', :country => 'Mexico', :track_type => 'Race circuit', :length => 4.304, :race_laps => 71, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Mexico_Circuit.png')
Track.create(:name => 'Sao Paulo Grand Prix', :country => 'Brazil', :track_type => 'Race circuit', :length => 4.309, :race_laps => 71, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Brazil_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Qatari Grand Prix', :country => 'Qatar', :track_type => 'Race circuit', :length => 5.38, :race_laps => 58, :image => 'https://www.pngkit.com/png/full/92-921661_losail-international-circuit-qatar-circuit-motogp.png')
Track.create(:name => 'Saudi Arabian Grand Prix', :country => 'Saudi Arabia', :track_type => 'Street circuit', :length => 6.174, :race_laps => 50, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Saudi_Arabia_Circuit.png.transform/9col/image.png')
Track.create(:name => 'Abu Dhabi Grand Prix', :country => 'United Arab Emirates', :track_type => 'Race Circuit', :length => 5.281, :race_laps => 55, :image => 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Abu_Dhabi_Circuit.png')

puts "#{Track.count} entries created."


Post.destroy_all














# anchor
